export type Category =
  | "Social"
  | "Search"
  | "Shopping"
  | "News"
  | "Entertainment"
  | "Education"
  | "Business"
  | "Health"
  | "Gaming"
  | "Tech"
  | "Environment"
  | "Finance"
  | "Fashion"
  | "FoodAndDining"
  | "Productivity"
  | "Community"
  | "Travel"
  | "Other";

export const categoryKeywords: Record<Category, string[]> = {
  Social: [
    "social",
    "friends",
    "connect",
    "network",
    "community",
    "interaction",
    "chat",
    "likes",
    "followers",
    "shares",
    "messaging",
  ],
  Shopping: [
    "shop",
    "buy",
    "cart",
    "ecommerce",
    "Amazon",
    "store",
    "purchase",
    "sale",
    "discount",
    "delivery",
    "wishlist",
    "offers",
  ],
  News: [
    "news",
    "articles",
    "updates",
    "blog",
    "CNN",
    "BBC",
    "headlines",
    "breaking",
    "current events",
    "media",
    "journals",
    "reporting",
  ],
  Entertainment: [
    "stream",
    "Netflix",
    "movies",
    "TV",
    "music",
    "YouTube",
    "binge-watch",
    "series",
    "gaming",
    "podcast",
    "comedy",
    "trailers",
  ],
  Education: [
    "learn",
    "course",
    "tutorial",
    "educational",
    "Udemy",
    "students",
    "resources",
    "assignments",
    "lectures",
    "skills",
    "workshops",
  ],
  Business: [
    "business",
    "finance",
    "market",
    "organization",
    "payroll",
    "startup",
    "corporate",
    "management",
    "profits",
    "investments",
    "strategy",
    "meetings",
  ],
  Health: [
    "health",
    "wellness",
    "fitness",
    "medical",
    "WebMD",
    "nutrition",
    "diet",
    "exercise",
    "symptoms",
    "care",
    "treatment",
    "mental health",
  ],
  Tech: [
    "tech",
    "software",
    "development",
    "coding",
    "GitHub",
    "AI",
    "machine learning",
    "innovation",
    "apps",
    "hardware",
    "cloud computing",
    "cybersecurity",
  ],
  Productivity: [
    "productivity",
    "task",
    "automation",
    "efficiency",
    "Notion",
    "time management",
    "planning",
    "reminders",
    "scheduling",
    "tracking",
    "workflow",
  ],
  Community: [
    "forum",
    "discussion",
    "Reddit",
    "Quora",
    "Discord",
    "social groups",
    "opinions",
    "threads",
    "Q&A",
    "help",
    "network",
    "local groups",
  ],
  Travel: [
    "travel",
    "trip",
    "hotel",
    "flight",
    "Airbnb",
    "Expedia",
    "destination",
    "tourism",
    "vacation",
    "itinerary",
    "exploration",
    "booking",
  ],
  Gaming: [
    "games",
    "play",
    "console",
    "PC",
    "mobile",
    "streaming",
    "Twitch",
    "multiplayer",
    "strategy",
    "quests",
    "leaderboards",
    "esports",
  ],
  FoodAndDining: [
    "food",
    "recipes",
    "restaurant",
    "delivery",
    "cooking",
    "chef",
    "ingredients",
    "cuisine",
    "reviews",
    "takeout",
    "reservations",
    "meals",
  ],
  Environment: [
    "eco",
    "green",
    "sustainability",
    "renewable",
    "climate",
    "wildlife",
    "conservation",
    "pollution",
    "ecosystem",
    "biodiversity",
    "recycling",
    "natural resources",
  ],
  Finance: [
    "investment",
    "banking",
    "tax",
    "credit",
    "savings",
    "budget",
    "wealth",
    "income",
    "stock market",
    "insurance",
    "cryptocurrency",
    "retirement planning",
  ],
  Fashion: [
    "clothing",
    "style",
    "apparel",
    "outfits",
    "trends",
    "accessories",
    "wardrobe",
    "runway",
    "couture",
    "luxury",
    "seasonal wear",
    "styling tips",
  ],
  Search: [
    "search",
    "engine",
    "Google",
    "Bing",
    "query",
    "browser",
    "find",
    "research",
    "discovery",
    "answers",
    "solutions",
    "keywords",
  ],
  Other: [],
};
